### ISSUE TITLE
Search for empty string

### ISSUE THREAD

**Issue by Palledaman** [genomizer/genomizer-server#324]
When search for empty string the webclient gets:

NEW EXCHANGE: GET /search/?annotations=
Trying to authenticate token 3b410c67-8e26-4910-8746-71cddb2c2710...
User testuser authenticated successfully.
Request body: 
{}
Could not parse query
Response body: 
{"message":"ERROR : Could not parse query"}

**Comment by tastyburger** [comment]
The thing is that the current implementation requires that for each name in the query in the URI, a corresponding value should be attached. If it does not correspond to this URI formatting, then an error is issued. But further down the line, there is a check specifically for the `annotations` name in the query, and if it is empty then the value is defaulted to `[expID]`.

Could be fixed by being more lenient regarding how the URI should be formatted.

**Comment by tastyburger** [comment]
Fixed in db2278cbff. Do `git fetch` then `git checkout EmptyStringFix`. Let me know if it broke something else.
