### ISSUE TITLE
Does exiting without logging out 20ish times do wierd things? (YES)

### ISSUE THREAD

**Issue by rednatto** [genomizer/genomizer-server#406]
Entering and exiting without logout a bunch of times (10+) seems to give some weird issues.
The login authentication is passed, but the later request authorizations seems to fail!
We should either not be allowed to log in, or, rather, not force our users to logout.

**Comment by yakrar** [comment]
Just to clarify: this happens if one does the following:

* Start the client
* Log in
* Exit without logging out
* Repeat the above 10-20 times

Is that correct?

**Comment by rednatto** [comment]
Something like that yes, using the same account name (the others will still work).
I do believe that we do not log out ( send the logout request ) when exiting the client.

**Comment by tastyburger** [comment]
I'm not sure about the current implementation, but I think the expected behavior should be: 
Set N to be the maximum number of simultaneous logins. Save the time of a particular login to be the login time or the time of the latest request if there is any such. If the same user has made N logins and attempts to make another, then the oldest login should be removed.

Does that sound reasonable? There is also a cleaner that removes inactive user every X time, I think it's currently set to an hour.

**Comment by parrexion** [comment]
The current implementation is supposed to work like you discribed. If it doesn' t then there's something off.

**Comment by tnaeg** [comment]
To clarify: The current implementation allows for 10 simultaneous logins from one user, when the 11th login attempts comes the oldest is removed and overtaken by the latest login.
