### ISSUE TITLE
GenomeReleaseConverterTest is ignored

### ISSUE THREAD

**Issue by 23Skidoo** [genomizer/genomizer-server#435]
Please either fix or remove it. No need to keep dead code in the tree, that's what Git is for.

**Comment by Mintey** [comment]
Indeed. @yakrar?

**Comment by yakrar** [comment]
@Mintey Actually, this isn't one of ours. @23Skidoo and Adam (not sure what his github id is) seem to be the only two that have actually touched the `GenomeReleaseConverter` class this year.

That said, the test has been ignored since mid April and no-one seems to have minded. I'll submit a pr to have it removed.

**Comment by 23Skidoo** [comment]
> not sure what his github id is

@knownsoldier
